- hosts: minecraft
  become: true

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Pull Minecraft server image
      docker_image:
        name: itzg/minecraft-server
        source: pull

    - name: Run Minecraft container
      docker_container:
        name: mc
        image: itzg/minecraft-server
        state: started
        restart_policy: always
        published_ports:
          - "25565:25565"
        volumes:
          - mc-data:/data

    - name: Create systemd service file
      copy:
        dest: /etc/systemd/system/minecraft-docker.service
        content: |
          [Unit]
          Description=minecraft docker
          After=docker.service
          Requires=docker.service

          [Service]
          Restart=always
          ExecStart=/usr/bin/docker start -a mc
          ExecStop=/usr/bin/docker stop -t 2 mc

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Enable and start service
      systemd:
        name: minecraft-docker
        enabled: yes
        state: restarted
